// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api.proto

package archive

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetFirstRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetFirstRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFirstRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFirstRequestMultiError, or nil if none found.
func (m *GetFirstRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFirstRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetFirstRequestMultiError(errors)
	}

	return nil
}

// GetFirstRequestMultiError is an error wrapping multiple validation errors
// returned by GetFirstRequest.ValidateAll() if the designated constraints
// aren't met.
type GetFirstRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFirstRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFirstRequestMultiError) AllErrors() []error { return m }

// GetFirstRequestValidationError is the validation error returned by
// GetFirstRequest.Validate if the designated constraints aren't met.
type GetFirstRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFirstRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFirstRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFirstRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFirstRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFirstRequestValidationError) ErrorName() string { return "GetFirstRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetFirstRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFirstRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFirstRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFirstRequestValidationError{}

// Validate checks the field values on GetFirstResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetFirstResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFirstResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFirstResponseMultiError, or nil if none found.
func (m *GetFirstResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFirstResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetHeight() <= 0 {
		err := GetFirstResponseValidationError{
			field:  "Height",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetFirstResponseMultiError(errors)
	}

	return nil
}

// GetFirstResponseMultiError is an error wrapping multiple validation errors
// returned by GetFirstResponse.ValidateAll() if the designated constraints
// aren't met.
type GetFirstResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFirstResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFirstResponseMultiError) AllErrors() []error { return m }

// GetFirstResponseValidationError is the validation error returned by
// GetFirstResponse.Validate if the designated constraints aren't met.
type GetFirstResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFirstResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFirstResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFirstResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFirstResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFirstResponseValidationError) ErrorName() string { return "GetFirstResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetFirstResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFirstResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFirstResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFirstResponseValidationError{}

// Validate checks the field values on GetLastRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetLastRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLastRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetLastRequestMultiError,
// or nil if none found.
func (m *GetLastRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLastRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetLastRequestMultiError(errors)
	}

	return nil
}

// GetLastRequestMultiError is an error wrapping multiple validation errors
// returned by GetLastRequest.ValidateAll() if the designated constraints
// aren't met.
type GetLastRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLastRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLastRequestMultiError) AllErrors() []error { return m }

// GetLastRequestValidationError is the validation error returned by
// GetLastRequest.Validate if the designated constraints aren't met.
type GetLastRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLastRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLastRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLastRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLastRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLastRequestValidationError) ErrorName() string { return "GetLastRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetLastRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLastRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLastRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLastRequestValidationError{}

// Validate checks the field values on GetLastResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetLastResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLastResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetLastResponseMultiError, or nil if none found.
func (m *GetLastResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLastResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Height

	if len(errors) > 0 {
		return GetLastResponseMultiError(errors)
	}

	return nil
}

// GetLastResponseMultiError is an error wrapping multiple validation errors
// returned by GetLastResponse.ValidateAll() if the designated constraints
// aren't met.
type GetLastResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLastResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLastResponseMultiError) AllErrors() []error { return m }

// GetLastResponseValidationError is the validation error returned by
// GetLastResponse.Validate if the designated constraints aren't met.
type GetLastResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLastResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLastResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLastResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLastResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLastResponseValidationError) ErrorName() string { return "GetLastResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetLastResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLastResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLastResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLastResponseValidationError{}

// Validate checks the field values on GetHeightForBlockRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetHeightForBlockRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetHeightForBlockRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetHeightForBlockRequestMultiError, or nil if none found.
func (m *GetHeightForBlockRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetHeightForBlockRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetBlockID()) != 32 {
		err := GetHeightForBlockRequestValidationError{
			field:  "BlockID",
			reason: "value length must be 32 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetHeightForBlockRequestMultiError(errors)
	}

	return nil
}

// GetHeightForBlockRequestMultiError is an error wrapping multiple validation
// errors returned by GetHeightForBlockRequest.ValidateAll() if the designated
// constraints aren't met.
type GetHeightForBlockRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetHeightForBlockRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetHeightForBlockRequestMultiError) AllErrors() []error { return m }

// GetHeightForBlockRequestValidationError is the validation error returned by
// GetHeightForBlockRequest.Validate if the designated constraints aren't met.
type GetHeightForBlockRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetHeightForBlockRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetHeightForBlockRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetHeightForBlockRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetHeightForBlockRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetHeightForBlockRequestValidationError) ErrorName() string {
	return "GetHeightForBlockRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetHeightForBlockRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetHeightForBlockRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetHeightForBlockRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetHeightForBlockRequestValidationError{}

// Validate checks the field values on GetHeightForBlockResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetHeightForBlockResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetHeightForBlockResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetHeightForBlockResponseMultiError, or nil if none found.
func (m *GetHeightForBlockResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetHeightForBlockResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BlockID

	// no validation rules for Height

	if len(errors) > 0 {
		return GetHeightForBlockResponseMultiError(errors)
	}

	return nil
}

// GetHeightForBlockResponseMultiError is an error wrapping multiple validation
// errors returned by GetHeightForBlockResponse.ValidateAll() if the
// designated constraints aren't met.
type GetHeightForBlockResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetHeightForBlockResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetHeightForBlockResponseMultiError) AllErrors() []error { return m }

// GetHeightForBlockResponseValidationError is the validation error returned by
// GetHeightForBlockResponse.Validate if the designated constraints aren't met.
type GetHeightForBlockResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetHeightForBlockResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetHeightForBlockResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetHeightForBlockResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetHeightForBlockResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetHeightForBlockResponseValidationError) ErrorName() string {
	return "GetHeightForBlockResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetHeightForBlockResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetHeightForBlockResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetHeightForBlockResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetHeightForBlockResponseValidationError{}

// Validate checks the field values on GetCommitRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetCommitRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCommitRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCommitRequestMultiError, or nil if none found.
func (m *GetCommitRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCommitRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetHeight() <= 0 {
		err := GetCommitRequestValidationError{
			field:  "Height",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetCommitRequestMultiError(errors)
	}

	return nil
}

// GetCommitRequestMultiError is an error wrapping multiple validation errors
// returned by GetCommitRequest.ValidateAll() if the designated constraints
// aren't met.
type GetCommitRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCommitRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCommitRequestMultiError) AllErrors() []error { return m }

// GetCommitRequestValidationError is the validation error returned by
// GetCommitRequest.Validate if the designated constraints aren't met.
type GetCommitRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCommitRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCommitRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCommitRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCommitRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCommitRequestValidationError) ErrorName() string { return "GetCommitRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetCommitRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCommitRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCommitRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCommitRequestValidationError{}

// Validate checks the field values on GetCommitResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetCommitResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCommitResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCommitResponseMultiError, or nil if none found.
func (m *GetCommitResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCommitResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Height

	// no validation rules for Commit

	if len(errors) > 0 {
		return GetCommitResponseMultiError(errors)
	}

	return nil
}

// GetCommitResponseMultiError is an error wrapping multiple validation errors
// returned by GetCommitResponse.ValidateAll() if the designated constraints
// aren't met.
type GetCommitResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCommitResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCommitResponseMultiError) AllErrors() []error { return m }

// GetCommitResponseValidationError is the validation error returned by
// GetCommitResponse.Validate if the designated constraints aren't met.
type GetCommitResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCommitResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCommitResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCommitResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCommitResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCommitResponseValidationError) ErrorName() string {
	return "GetCommitResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetCommitResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCommitResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCommitResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCommitResponseValidationError{}

// Validate checks the field values on GetHeaderRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetHeaderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetHeaderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetHeaderRequestMultiError, or nil if none found.
func (m *GetHeaderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetHeaderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetHeight() <= 0 {
		err := GetHeaderRequestValidationError{
			field:  "Height",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetHeaderRequestMultiError(errors)
	}

	return nil
}

// GetHeaderRequestMultiError is an error wrapping multiple validation errors
// returned by GetHeaderRequest.ValidateAll() if the designated constraints
// aren't met.
type GetHeaderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetHeaderRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetHeaderRequestMultiError) AllErrors() []error { return m }

// GetHeaderRequestValidationError is the validation error returned by
// GetHeaderRequest.Validate if the designated constraints aren't met.
type GetHeaderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetHeaderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetHeaderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetHeaderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetHeaderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetHeaderRequestValidationError) ErrorName() string { return "GetHeaderRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetHeaderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetHeaderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetHeaderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetHeaderRequestValidationError{}

// Validate checks the field values on GetHeaderResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetHeaderResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetHeaderResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetHeaderResponseMultiError, or nil if none found.
func (m *GetHeaderResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetHeaderResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Height

	// no validation rules for Data

	if len(errors) > 0 {
		return GetHeaderResponseMultiError(errors)
	}

	return nil
}

// GetHeaderResponseMultiError is an error wrapping multiple validation errors
// returned by GetHeaderResponse.ValidateAll() if the designated constraints
// aren't met.
type GetHeaderResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetHeaderResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetHeaderResponseMultiError) AllErrors() []error { return m }

// GetHeaderResponseValidationError is the validation error returned by
// GetHeaderResponse.Validate if the designated constraints aren't met.
type GetHeaderResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetHeaderResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetHeaderResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetHeaderResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetHeaderResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetHeaderResponseValidationError) ErrorName() string {
	return "GetHeaderResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetHeaderResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetHeaderResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetHeaderResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetHeaderResponseValidationError{}

// Validate checks the field values on GetEventsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetEventsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEventsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEventsRequestMultiError, or nil if none found.
func (m *GetEventsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEventsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetHeight() <= 0 {
		err := GetEventsRequestValidationError{
			field:  "Height",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetEventsRequestMultiError(errors)
	}

	return nil
}

// GetEventsRequestMultiError is an error wrapping multiple validation errors
// returned by GetEventsRequest.ValidateAll() if the designated constraints
// aren't met.
type GetEventsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEventsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEventsRequestMultiError) AllErrors() []error { return m }

// GetEventsRequestValidationError is the validation error returned by
// GetEventsRequest.Validate if the designated constraints aren't met.
type GetEventsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEventsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEventsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEventsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEventsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEventsRequestValidationError) ErrorName() string { return "GetEventsRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetEventsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEventsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEventsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEventsRequestValidationError{}

// Validate checks the field values on GetEventsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetEventsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEventsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEventsResponseMultiError, or nil if none found.
func (m *GetEventsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEventsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Height

	// no validation rules for Data

	if len(errors) > 0 {
		return GetEventsResponseMultiError(errors)
	}

	return nil
}

// GetEventsResponseMultiError is an error wrapping multiple validation errors
// returned by GetEventsResponse.ValidateAll() if the designated constraints
// aren't met.
type GetEventsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEventsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEventsResponseMultiError) AllErrors() []error { return m }

// GetEventsResponseValidationError is the validation error returned by
// GetEventsResponse.Validate if the designated constraints aren't met.
type GetEventsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEventsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEventsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEventsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEventsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEventsResponseValidationError) ErrorName() string {
	return "GetEventsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetEventsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEventsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEventsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEventsResponseValidationError{}

// Validate checks the field values on GetRegisterValuesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRegisterValuesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRegisterValuesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRegisterValuesRequestMultiError, or nil if none found.
func (m *GetRegisterValuesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRegisterValuesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetHeight() <= 0 {
		err := GetRegisterValuesRequestValidationError{
			field:  "Height",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetPaths()) < 1 {
		err := GetRegisterValuesRequestValidationError{
			field:  "Paths",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetPaths() {
		_, _ = idx, item

		if len(item) != 32 {
			err := GetRegisterValuesRequestValidationError{
				field:  fmt.Sprintf("Paths[%v]", idx),
				reason: "value length must be 32 bytes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return GetRegisterValuesRequestMultiError(errors)
	}

	return nil
}

// GetRegisterValuesRequestMultiError is an error wrapping multiple validation
// errors returned by GetRegisterValuesRequest.ValidateAll() if the designated
// constraints aren't met.
type GetRegisterValuesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRegisterValuesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRegisterValuesRequestMultiError) AllErrors() []error { return m }

// GetRegisterValuesRequestValidationError is the validation error returned by
// GetRegisterValuesRequest.Validate if the designated constraints aren't met.
type GetRegisterValuesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRegisterValuesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRegisterValuesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRegisterValuesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRegisterValuesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRegisterValuesRequestValidationError) ErrorName() string {
	return "GetRegisterValuesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRegisterValuesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRegisterValuesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRegisterValuesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRegisterValuesRequestValidationError{}

// Validate checks the field values on GetRegisterValuesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRegisterValuesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRegisterValuesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRegisterValuesResponseMultiError, or nil if none found.
func (m *GetRegisterValuesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRegisterValuesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Height

	if len(errors) > 0 {
		return GetRegisterValuesResponseMultiError(errors)
	}

	return nil
}

// GetRegisterValuesResponseMultiError is an error wrapping multiple validation
// errors returned by GetRegisterValuesResponse.ValidateAll() if the
// designated constraints aren't met.
type GetRegisterValuesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRegisterValuesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRegisterValuesResponseMultiError) AllErrors() []error { return m }

// GetRegisterValuesResponseValidationError is the validation error returned by
// GetRegisterValuesResponse.Validate if the designated constraints aren't met.
type GetRegisterValuesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRegisterValuesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRegisterValuesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRegisterValuesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRegisterValuesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRegisterValuesResponseValidationError) ErrorName() string {
	return "GetRegisterValuesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRegisterValuesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRegisterValuesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRegisterValuesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRegisterValuesResponseValidationError{}

// Validate checks the field values on GetCollectionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCollectionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCollectionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCollectionRequestMultiError, or nil if none found.
func (m *GetCollectionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCollectionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetCollectionID()) != 32 {
		err := GetCollectionRequestValidationError{
			field:  "CollectionID",
			reason: "value length must be 32 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetCollectionRequestMultiError(errors)
	}

	return nil
}

// GetCollectionRequestMultiError is an error wrapping multiple validation
// errors returned by GetCollectionRequest.ValidateAll() if the designated
// constraints aren't met.
type GetCollectionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCollectionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCollectionRequestMultiError) AllErrors() []error { return m }

// GetCollectionRequestValidationError is the validation error returned by
// GetCollectionRequest.Validate if the designated constraints aren't met.
type GetCollectionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCollectionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCollectionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCollectionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCollectionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCollectionRequestValidationError) ErrorName() string {
	return "GetCollectionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCollectionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCollectionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCollectionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCollectionRequestValidationError{}

// Validate checks the field values on GetCollectionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCollectionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCollectionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCollectionResponseMultiError, or nil if none found.
func (m *GetCollectionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCollectionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CollectionID

	// no validation rules for Data

	if len(errors) > 0 {
		return GetCollectionResponseMultiError(errors)
	}

	return nil
}

// GetCollectionResponseMultiError is an error wrapping multiple validation
// errors returned by GetCollectionResponse.ValidateAll() if the designated
// constraints aren't met.
type GetCollectionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCollectionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCollectionResponseMultiError) AllErrors() []error { return m }

// GetCollectionResponseValidationError is the validation error returned by
// GetCollectionResponse.Validate if the designated constraints aren't met.
type GetCollectionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCollectionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCollectionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCollectionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCollectionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCollectionResponseValidationError) ErrorName() string {
	return "GetCollectionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetCollectionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCollectionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCollectionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCollectionResponseValidationError{}

// Validate checks the field values on ListCollectionsForHeightRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListCollectionsForHeightRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCollectionsForHeightRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListCollectionsForHeightRequestMultiError, or nil if none found.
func (m *ListCollectionsForHeightRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCollectionsForHeightRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetHeight() <= 0 {
		err := ListCollectionsForHeightRequestValidationError{
			field:  "Height",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListCollectionsForHeightRequestMultiError(errors)
	}

	return nil
}

// ListCollectionsForHeightRequestMultiError is an error wrapping multiple
// validation errors returned by ListCollectionsForHeightRequest.ValidateAll()
// if the designated constraints aren't met.
type ListCollectionsForHeightRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCollectionsForHeightRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCollectionsForHeightRequestMultiError) AllErrors() []error { return m }

// ListCollectionsForHeightRequestValidationError is the validation error
// returned by ListCollectionsForHeightRequest.Validate if the designated
// constraints aren't met.
type ListCollectionsForHeightRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCollectionsForHeightRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCollectionsForHeightRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCollectionsForHeightRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCollectionsForHeightRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCollectionsForHeightRequestValidationError) ErrorName() string {
	return "ListCollectionsForHeightRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListCollectionsForHeightRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCollectionsForHeightRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCollectionsForHeightRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCollectionsForHeightRequestValidationError{}

// Validate checks the field values on ListCollectionsForHeightResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListCollectionsForHeightResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCollectionsForHeightResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListCollectionsForHeightResponseMultiError, or nil if none found.
func (m *ListCollectionsForHeightResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCollectionsForHeightResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Height

	if len(errors) > 0 {
		return ListCollectionsForHeightResponseMultiError(errors)
	}

	return nil
}

// ListCollectionsForHeightResponseMultiError is an error wrapping multiple
// validation errors returned by
// ListCollectionsForHeightResponse.ValidateAll() if the designated
// constraints aren't met.
type ListCollectionsForHeightResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCollectionsForHeightResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCollectionsForHeightResponseMultiError) AllErrors() []error { return m }

// ListCollectionsForHeightResponseValidationError is the validation error
// returned by ListCollectionsForHeightResponse.Validate if the designated
// constraints aren't met.
type ListCollectionsForHeightResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCollectionsForHeightResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCollectionsForHeightResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCollectionsForHeightResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCollectionsForHeightResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCollectionsForHeightResponseValidationError) ErrorName() string {
	return "ListCollectionsForHeightResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListCollectionsForHeightResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCollectionsForHeightResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCollectionsForHeightResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCollectionsForHeightResponseValidationError{}

// Validate checks the field values on GetGuaranteeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGuaranteeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGuaranteeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGuaranteeRequestMultiError, or nil if none found.
func (m *GetGuaranteeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGuaranteeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetCollectionID()) != 32 {
		err := GetGuaranteeRequestValidationError{
			field:  "CollectionID",
			reason: "value length must be 32 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetGuaranteeRequestMultiError(errors)
	}

	return nil
}

// GetGuaranteeRequestMultiError is an error wrapping multiple validation
// errors returned by GetGuaranteeRequest.ValidateAll() if the designated
// constraints aren't met.
type GetGuaranteeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGuaranteeRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGuaranteeRequestMultiError) AllErrors() []error { return m }

// GetGuaranteeRequestValidationError is the validation error returned by
// GetGuaranteeRequest.Validate if the designated constraints aren't met.
type GetGuaranteeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGuaranteeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGuaranteeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGuaranteeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGuaranteeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGuaranteeRequestValidationError) ErrorName() string {
	return "GetGuaranteeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetGuaranteeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGuaranteeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGuaranteeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGuaranteeRequestValidationError{}

// Validate checks the field values on GetGuaranteeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGuaranteeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGuaranteeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGuaranteeResponseMultiError, or nil if none found.
func (m *GetGuaranteeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGuaranteeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CollectionID

	// no validation rules for Data

	if len(errors) > 0 {
		return GetGuaranteeResponseMultiError(errors)
	}

	return nil
}

// GetGuaranteeResponseMultiError is an error wrapping multiple validation
// errors returned by GetGuaranteeResponse.ValidateAll() if the designated
// constraints aren't met.
type GetGuaranteeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGuaranteeResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGuaranteeResponseMultiError) AllErrors() []error { return m }

// GetGuaranteeResponseValidationError is the validation error returned by
// GetGuaranteeResponse.Validate if the designated constraints aren't met.
type GetGuaranteeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGuaranteeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGuaranteeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGuaranteeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGuaranteeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGuaranteeResponseValidationError) ErrorName() string {
	return "GetGuaranteeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetGuaranteeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGuaranteeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGuaranteeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGuaranteeResponseValidationError{}

// Validate checks the field values on GetTransactionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTransactionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTransactionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTransactionRequestMultiError, or nil if none found.
func (m *GetTransactionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetTransactionID()) != 32 {
		err := GetTransactionRequestValidationError{
			field:  "TransactionID",
			reason: "value length must be 32 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetTransactionRequestMultiError(errors)
	}

	return nil
}

// GetTransactionRequestMultiError is an error wrapping multiple validation
// errors returned by GetTransactionRequest.ValidateAll() if the designated
// constraints aren't met.
type GetTransactionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionRequestMultiError) AllErrors() []error { return m }

// GetTransactionRequestValidationError is the validation error returned by
// GetTransactionRequest.Validate if the designated constraints aren't met.
type GetTransactionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionRequestValidationError) ErrorName() string {
	return "GetTransactionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionRequestValidationError{}

// Validate checks the field values on GetTransactionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTransactionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTransactionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTransactionResponseMultiError, or nil if none found.
func (m *GetTransactionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TransactionID

	// no validation rules for Data

	if len(errors) > 0 {
		return GetTransactionResponseMultiError(errors)
	}

	return nil
}

// GetTransactionResponseMultiError is an error wrapping multiple validation
// errors returned by GetTransactionResponse.ValidateAll() if the designated
// constraints aren't met.
type GetTransactionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionResponseMultiError) AllErrors() []error { return m }

// GetTransactionResponseValidationError is the validation error returned by
// GetTransactionResponse.Validate if the designated constraints aren't met.
type GetTransactionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionResponseValidationError) ErrorName() string {
	return "GetTransactionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionResponseValidationError{}

// Validate checks the field values on GetHeightForTransactionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetHeightForTransactionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetHeightForTransactionRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetHeightForTransactionRequestMultiError, or nil if none found.
func (m *GetHeightForTransactionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetHeightForTransactionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetTransactionID()) != 32 {
		err := GetHeightForTransactionRequestValidationError{
			field:  "TransactionID",
			reason: "value length must be 32 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetHeightForTransactionRequestMultiError(errors)
	}

	return nil
}

// GetHeightForTransactionRequestMultiError is an error wrapping multiple
// validation errors returned by GetHeightForTransactionRequest.ValidateAll()
// if the designated constraints aren't met.
type GetHeightForTransactionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetHeightForTransactionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetHeightForTransactionRequestMultiError) AllErrors() []error { return m }

// GetHeightForTransactionRequestValidationError is the validation error
// returned by GetHeightForTransactionRequest.Validate if the designated
// constraints aren't met.
type GetHeightForTransactionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetHeightForTransactionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetHeightForTransactionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetHeightForTransactionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetHeightForTransactionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetHeightForTransactionRequestValidationError) ErrorName() string {
	return "GetHeightForTransactionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetHeightForTransactionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetHeightForTransactionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetHeightForTransactionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetHeightForTransactionRequestValidationError{}

// Validate checks the field values on GetHeightForTransactionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetHeightForTransactionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetHeightForTransactionResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetHeightForTransactionResponseMultiError, or nil if none found.
func (m *GetHeightForTransactionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetHeightForTransactionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TransactionID

	// no validation rules for Height

	if len(errors) > 0 {
		return GetHeightForTransactionResponseMultiError(errors)
	}

	return nil
}

// GetHeightForTransactionResponseMultiError is an error wrapping multiple
// validation errors returned by GetHeightForTransactionResponse.ValidateAll()
// if the designated constraints aren't met.
type GetHeightForTransactionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetHeightForTransactionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetHeightForTransactionResponseMultiError) AllErrors() []error { return m }

// GetHeightForTransactionResponseValidationError is the validation error
// returned by GetHeightForTransactionResponse.Validate if the designated
// constraints aren't met.
type GetHeightForTransactionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetHeightForTransactionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetHeightForTransactionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetHeightForTransactionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetHeightForTransactionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetHeightForTransactionResponseValidationError) ErrorName() string {
	return "GetHeightForTransactionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetHeightForTransactionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetHeightForTransactionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetHeightForTransactionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetHeightForTransactionResponseValidationError{}

// Validate checks the field values on ListTransactionsForHeightRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListTransactionsForHeightRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTransactionsForHeightRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListTransactionsForHeightRequestMultiError, or nil if none found.
func (m *ListTransactionsForHeightRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTransactionsForHeightRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetHeight() <= 0 {
		err := ListTransactionsForHeightRequestValidationError{
			field:  "Height",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListTransactionsForHeightRequestMultiError(errors)
	}

	return nil
}

// ListTransactionsForHeightRequestMultiError is an error wrapping multiple
// validation errors returned by
// ListTransactionsForHeightRequest.ValidateAll() if the designated
// constraints aren't met.
type ListTransactionsForHeightRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTransactionsForHeightRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTransactionsForHeightRequestMultiError) AllErrors() []error { return m }

// ListTransactionsForHeightRequestValidationError is the validation error
// returned by ListTransactionsForHeightRequest.Validate if the designated
// constraints aren't met.
type ListTransactionsForHeightRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTransactionsForHeightRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTransactionsForHeightRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTransactionsForHeightRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTransactionsForHeightRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTransactionsForHeightRequestValidationError) ErrorName() string {
	return "ListTransactionsForHeightRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListTransactionsForHeightRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTransactionsForHeightRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTransactionsForHeightRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTransactionsForHeightRequestValidationError{}

// Validate checks the field values on ListTransactionsForHeightResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListTransactionsForHeightResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTransactionsForHeightResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ListTransactionsForHeightResponseMultiError, or nil if none found.
func (m *ListTransactionsForHeightResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTransactionsForHeightResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Height

	if len(errors) > 0 {
		return ListTransactionsForHeightResponseMultiError(errors)
	}

	return nil
}

// ListTransactionsForHeightResponseMultiError is an error wrapping multiple
// validation errors returned by
// ListTransactionsForHeightResponse.ValidateAll() if the designated
// constraints aren't met.
type ListTransactionsForHeightResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTransactionsForHeightResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTransactionsForHeightResponseMultiError) AllErrors() []error { return m }

// ListTransactionsForHeightResponseValidationError is the validation error
// returned by ListTransactionsForHeightResponse.Validate if the designated
// constraints aren't met.
type ListTransactionsForHeightResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTransactionsForHeightResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTransactionsForHeightResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTransactionsForHeightResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTransactionsForHeightResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTransactionsForHeightResponseValidationError) ErrorName() string {
	return "ListTransactionsForHeightResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListTransactionsForHeightResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTransactionsForHeightResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTransactionsForHeightResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTransactionsForHeightResponseValidationError{}

// Validate checks the field values on GetResultRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetResultRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetResultRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetResultRequestMultiError, or nil if none found.
func (m *GetResultRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetResultRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetTransactionID()) != 32 {
		err := GetResultRequestValidationError{
			field:  "TransactionID",
			reason: "value length must be 32 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetResultRequestMultiError(errors)
	}

	return nil
}

// GetResultRequestMultiError is an error wrapping multiple validation errors
// returned by GetResultRequest.ValidateAll() if the designated constraints
// aren't met.
type GetResultRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetResultRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetResultRequestMultiError) AllErrors() []error { return m }

// GetResultRequestValidationError is the validation error returned by
// GetResultRequest.Validate if the designated constraints aren't met.
type GetResultRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetResultRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetResultRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetResultRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetResultRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetResultRequestValidationError) ErrorName() string { return "GetResultRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetResultRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetResultRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetResultRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetResultRequestValidationError{}

// Validate checks the field values on GetResultResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetResultResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetResultResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetResultResponseMultiError, or nil if none found.
func (m *GetResultResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetResultResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TransactionID

	// no validation rules for Data

	if len(errors) > 0 {
		return GetResultResponseMultiError(errors)
	}

	return nil
}

// GetResultResponseMultiError is an error wrapping multiple validation errors
// returned by GetResultResponse.ValidateAll() if the designated constraints
// aren't met.
type GetResultResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetResultResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetResultResponseMultiError) AllErrors() []error { return m }

// GetResultResponseValidationError is the validation error returned by
// GetResultResponse.Validate if the designated constraints aren't met.
type GetResultResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetResultResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetResultResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetResultResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetResultResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetResultResponseValidationError) ErrorName() string {
	return "GetResultResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetResultResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetResultResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetResultResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetResultResponseValidationError{}

// Validate checks the field values on GetSealRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetSealRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSealRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetSealRequestMultiError,
// or nil if none found.
func (m *GetSealRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSealRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetSealID()) != 32 {
		err := GetSealRequestValidationError{
			field:  "SealID",
			reason: "value length must be 32 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetSealRequestMultiError(errors)
	}

	return nil
}

// GetSealRequestMultiError is an error wrapping multiple validation errors
// returned by GetSealRequest.ValidateAll() if the designated constraints
// aren't met.
type GetSealRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSealRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSealRequestMultiError) AllErrors() []error { return m }

// GetSealRequestValidationError is the validation error returned by
// GetSealRequest.Validate if the designated constraints aren't met.
type GetSealRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSealRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSealRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSealRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSealRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSealRequestValidationError) ErrorName() string { return "GetSealRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetSealRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSealRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSealRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSealRequestValidationError{}

// Validate checks the field values on GetSealResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetSealResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSealResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSealResponseMultiError, or nil if none found.
func (m *GetSealResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSealResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SealID

	// no validation rules for Data

	if len(errors) > 0 {
		return GetSealResponseMultiError(errors)
	}

	return nil
}

// GetSealResponseMultiError is an error wrapping multiple validation errors
// returned by GetSealResponse.ValidateAll() if the designated constraints
// aren't met.
type GetSealResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSealResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSealResponseMultiError) AllErrors() []error { return m }

// GetSealResponseValidationError is the validation error returned by
// GetSealResponse.Validate if the designated constraints aren't met.
type GetSealResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSealResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSealResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSealResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSealResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSealResponseValidationError) ErrorName() string { return "GetSealResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetSealResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSealResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSealResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSealResponseValidationError{}

// Validate checks the field values on ListSealsForHeightRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListSealsForHeightRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSealsForHeightRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListSealsForHeightRequestMultiError, or nil if none found.
func (m *ListSealsForHeightRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSealsForHeightRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetHeight() <= 0 {
		err := ListSealsForHeightRequestValidationError{
			field:  "Height",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListSealsForHeightRequestMultiError(errors)
	}

	return nil
}

// ListSealsForHeightRequestMultiError is an error wrapping multiple validation
// errors returned by ListSealsForHeightRequest.ValidateAll() if the
// designated constraints aren't met.
type ListSealsForHeightRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSealsForHeightRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSealsForHeightRequestMultiError) AllErrors() []error { return m }

// ListSealsForHeightRequestValidationError is the validation error returned by
// ListSealsForHeightRequest.Validate if the designated constraints aren't met.
type ListSealsForHeightRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSealsForHeightRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSealsForHeightRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSealsForHeightRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSealsForHeightRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSealsForHeightRequestValidationError) ErrorName() string {
	return "ListSealsForHeightRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListSealsForHeightRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSealsForHeightRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSealsForHeightRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSealsForHeightRequestValidationError{}

// Validate checks the field values on ListSealsForHeightResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListSealsForHeightResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSealsForHeightResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListSealsForHeightResponseMultiError, or nil if none found.
func (m *ListSealsForHeightResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSealsForHeightResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Height

	if len(errors) > 0 {
		return ListSealsForHeightResponseMultiError(errors)
	}

	return nil
}

// ListSealsForHeightResponseMultiError is an error wrapping multiple
// validation errors returned by ListSealsForHeightResponse.ValidateAll() if
// the designated constraints aren't met.
type ListSealsForHeightResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSealsForHeightResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSealsForHeightResponseMultiError) AllErrors() []error { return m }

// ListSealsForHeightResponseValidationError is the validation error returned
// by ListSealsForHeightResponse.Validate if the designated constraints aren't met.
type ListSealsForHeightResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSealsForHeightResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSealsForHeightResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSealsForHeightResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSealsForHeightResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSealsForHeightResponseValidationError) ErrorName() string {
	return "ListSealsForHeightResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListSealsForHeightResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSealsForHeightResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSealsForHeightResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSealsForHeightResponseValidationError{}
